// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numberOfTimes = Integer.parseInt(args[0]);

		int i = 0;
		int countBigger = 0;
		int countSmaller = 0;

		// while loop that will genrate random numbers (the amount that received), and will count how much times we got a number thats bigger than 0.5, and how much times we got one samller or equal to 0.5
		while (i <= numberOfTimes) {
			double randomNumber = Math.random();
			if (randomNumber > 0.5) {
				countBigger++;
			} else {
				countSmaller++;
			}
			i++;
		}

		System.out.printf("> 0.5: %d times %n", countBigger);
		System.out.printf("<= 0.5: %d times %n", countSmaller);

		// Calculating the ratio - as long as countBigger and countSmaller is bogger than 1
		if ((countBigger > 0) && (countSmaller > 0)) {
			double ratio = (double)countBigger / countSmaller;
			System.out.printf("Ratio: %f %n", ratio);
		}
	}
}
